
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: dreport_development
  username: sifaho
  password: 12345678

test:
  <<: *default
  database: dreport_test
  username: sifaho
  password: 12345678

production:
  <<: *default
  database: dreport_production
  username: sifaho
  password: <%= ENV['DREPORT_DATABASE_PASSWORD'] %>
